export const FETCH_QUESTIONNAIRES = 'FETCH_QUESTIONNAIRES';
export const FETCH_QUESTIONNAIRES_SUCCESS = 'FETCH_QUESTIONNAIRES_SUCCESS';
export const FETCH_QUESTIONNAIRES_FAILURE = 'FETCH_QUESTIONNAIRES_FAILURE';
export const FETCH_QUESTIONNAIRES_REQUEST = 'FETCH_QUESTIONNAIRES_REQUEST'; 